<a href="https://colab.research.google.com/github/alemtgetu/602-health/blob/main/Neural_Net_Cancer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import pandas as pd
from google.colab import files

uploaded = files.upload() #select the file
cancer_data = pd.read_csv("Breast_Cancer_data.csv", sep=',') #read the data into the class dataframe

Saving Breast_Cancer_data.csv to Breast_Cancer_data.csv

In [5]:
cancer_data.describe() #there are 16 missing data points from the Bare Nuclei, we will replace the missing data with the average Bare Nuclei of the class of the missing data

          id number  Clump Thickness  ...     Mitoses       Class
count  6.990000e+02       699.000000  ...  699.000000  699.000000
mean   1.071704e+06         4.417740  ...    1.589413    2.689557
std    6.170957e+05         2.815741  ...    1.715078    0.951273
min    6.163400e+04         1.000000  ...    1.000000    2.000000
25%    8.706885e+05         2.000000  ...    1.000000    2.000000
50%    1.171710e+06         4.000000  ...    1.000000    2.000000
75%    1.238298e+06         6.000000  ...    1.000000    4.000000
max    1.345435e+07        10.000000  ...   10.000000    4.000000

[8 rows x 10 columns]

In [6]:
cancer_data.head()

   id number  Clump Thickness  ...  Mitoses  Class
0    1000025                5  ...        1      2
1    1002945                5  ...        1      2
2    1015425                3  ...        1      2
3    1016277                6  ...        1      2
4    1017023                4  ...        1      2

[5 rows x 11 columns]

In [7]:
data_filtered = cancer_data[cancer_data['Bare Nuclei'] != '?'] #remove rows with missing data
data_filtered = data_filtered.astype('int64')
data_filtered.dtypes

id number                      int64
Clump Thickness                int64
Uniformity of Cell Size        int64
Uniformity of Cell Shape       int64
Marginal Adhesion              int64
Single Epithelial Cell Size    int64
Bare Nuclei                    int64
Bland Chromatin                int64
Normal Nucleoli                int64
Mitoses                        int64
Class                          int64
dtype: object

In [8]:
mal_data = data_filtered[data_filtered['Class'] != 2] #all the malignant tumor data
mal_data.describe()

          id number  Clump Thickness  ...     Mitoses  Class
count  2.390000e+02       239.000000  ...  239.000000  239.0
mean   1.005121e+06         7.188285  ...    2.602510    4.0
std    3.223021e+05         2.437907  ...    2.564495    0.0
min    6.337500e+04         1.000000  ...    1.000000    4.0
25%    8.323965e+05         5.000000  ...    1.000000    4.0
50%    1.142706e+06         8.000000  ...    1.000000    4.0
75%    1.221955e+06        10.000000  ...    3.000000    4.0
max    1.371026e+06        10.000000  ...   10.000000    4.0

[8 rows x 11 columns]

In [9]:
ben_data = data_filtered[data_filtered['Class'] != 4] #all the benign 
ben_data.describe()

          id number  Clump Thickness  ...     Mitoses  Class
count  4.440000e+02       444.000000  ...  444.000000  444.0
mean   1.115261e+06         2.963964  ...    1.065315    2.0
std    7.300359e+05         1.672661  ...    0.509738    0.0
min    1.280590e+05         1.000000  ...    1.000000    2.0
25%    1.016064e+06         1.000000  ...    1.000000    2.0
50%    1.180677e+06         3.000000  ...    1.000000    2.0
75%    1.257846e+06         4.000000  ...    1.000000    2.0
max    1.345435e+07         8.000000  ...    8.000000    2.0

[8 rows x 11 columns]

In [10]:
can_dat = cancer_data.copy(deep = True)
def myfunc(Bare,Class):
  if Bare=='?' and Class == 2:
    Bare = 1
  elif Bare=='?' and Class == 4:
    Bare = 8
  else:
    Bare = Bare
  return Bare
can_dat['Bare Nuclei'] = can_dat.apply(lambda x: myfunc(x['Bare Nuclei'], x['Class']), axis =1)
can_dat = can_dat.astype('int64')
can_dat.dtypes
#list = can_dat['Bare Nuclei'].tolist()
#print(list)

id number                      int64
Clump Thickness                int64
Uniformity of Cell Size        int64
Uniformity of Cell Shape       int64
Marginal Adhesion              int64
Single Epithelial Cell Size    int64
Bare Nuclei                    int64
Bland Chromatin                int64
Normal Nucleoli                int64
Mitoses                        int64
Class                          int64
dtype: object

In [11]:
input_data = can_dat[['Clump Thickness', 'Uniformity of Cell Size','Uniformity of Cell Shape', 'Marginal Adhesion','Single Epithelial Cell Size', 'Bare Nuclei', 'Bland Chromatin', 'Normal Nucleoli', 'Mitoses']]
results_data = can_dat[['Class']]
input_data_train = input_data.iloc[:350,:]
input_data_test = input_data.iloc[351:,:]

results_data_train = results_data.iloc[:350,:]
results_data_test = results_data.iloc[351:,:]

In [12]:
from sklearn.tree import DecisionTreeRegressor #import decisiontreeregressor from the sklearn libary 
cancer_model = DecisionTreeRegressor(random_state=1) #this is the base nn
cancer_model.fit(input_data_train,results_data_train) #trains it with the x and y data sets

DecisionTreeRegressor(random_state=1)

In [13]:
from sklearn.metrics import mean_absolute_error
val_predictions = cancer_model.predict(input_data_test)

In [36]:
mean_absolute_error(results_data_test,val_predictions)

0.08620689655172414

In [75]:
predict = val_predictions.tolist()
actual = results_data_test.values.tolist()
for i in range(len(actual)):
  if predict[i] - actual[i][0] != 0:
    print(input_data_test.iloc[i])
    print("Model Prediction: " + str(predict[i]))
    print("Actual Result: " + str(actual[i][0]))
    print()

Clump Thickness                3
Uniformity of Cell Size        4
Uniformity of Cell Shape       5
Marginal Adhesion              3
Single Epithelial Cell Size    7
Bare Nuclei                    3
Bland Chromatin                4
Normal Nucleoli                6
Mitoses                        1
Name: 352, dtype: int64
Model Prediction: 4.0
Actual Result: 2

Clump Thickness                5
Uniformity of Cell Size        3
Uniformity of Cell Shape       3
Marginal Adhesion              1
Single Epithelial Cell Size    3
Bare Nuclei                    3
Bland Chromatin                3
Normal Nucleoli                3
Mitoses                        3
Name: 356, dtype: int64
Model Prediction: 2.0
Actual Result: 4

Clump Thickness                2
Uniformity of Cell Size        3
Uniformity of Cell Shape       1
Marginal Adhesion              1
Single Epithelial Cell Size    5
Bare Nuclei                    1
Bland Chromatin                1
Normal Nucleoli                1
Mitoses                        1
Name: 419, dtype: int64
Model Prediction: 4.0
Actual Result: 2

Clump Thickness                 8
Uniformity of Cell Size         7
Uniformity of Cell Shape        8
Marginal Adhesion               2
Single Epithelial Cell Size     4
Bare Nuclei                     2
Bland Chromatin                 5
Normal Nucleoli                10
Mitoses                         1
Name: 427, dtype: int64
Model Prediction: 2.0
Actual Result: 4

Clump Thickness                6
Uniformity of Cell Size        9
Uniformity of Cell Shape       7
Marginal Adhesion              5
Single Epithelial Cell Size    5
Bare Nuclei                    8
Bland Chromatin                4
Normal Nucleoli                2
Mitoses                        1
Name: 434, dtype: int64
Model Prediction: 4.0
Actual Result: 2

Clump Thickness                5
Uniformity of Cell Size        2
Uniformity of Cell Shape       2
Marginal Adhesion              4
Single Epithelial Cell Size    2
Bare Nuclei                    4
Bland Chromatin                1
Normal Nucleoli                1
Mitoses                        1
Name: 441, dtype: int64
Model Prediction: 4.0
Actual Result: 2

Clump Thickness                 3
Uniformity of Cell Size         6
Uniformity of Cell Shape        4
Marginal Adhesion              10
Single Epithelial Cell Size     3
Bare Nuclei                     3
Bland Chromatin                 3
Normal Nucleoli                 4
Mitoses                         1
Name: 488, dtype: int64
Model Prediction: 2.0
Actual Result: 4

Clump Thickness                6
Uniformity of Cell Size        3
Uniformity of Cell Shape       2
Marginal Adhesion              1
Single Epithelial Cell Size    3
Bare Nuclei                    4
Bland Chromatin                4
Normal Nucleoli                1
Mitoses                        1
Name: 489, dtype: int64
Model Prediction: 2.0
Actual Result: 4

Clump Thickness                 5
Uniformity of Cell Size         1
Uniformity of Cell Shape        2
Marginal Adhesion              10
Single Epithelial Cell Size     4
Bare Nuclei                     5
Bland Chromatin                 2
Normal Nucleoli                 1
Mitoses                         1
Name: 494, dtype: int64
Model Prediction: 4.0
Actual Result: 2

Clump Thickness                 7
Uniformity of Cell Size         4
Uniformity of Cell Shape        4
Marginal Adhesion               3
Single Epithelial Cell Size     4
Bare Nuclei                    10
Bland Chromatin                 6
Normal Nucleoli                 9
Mitoses                         1
Name: 530, dtype: int64
Model Prediction: 2.0
Actual Result: 4

Clump Thickness                 4
Uniformity of Cell Size        10
Uniformity of Cell Shape        8
Marginal Adhesion               5
Single Epithelial Cell Size     4
Bare Nuclei                     1
Bland Chromatin                10
Normal Nucleoli                 1
Mitoses                         1
Name: 590, dtype: int64
Model Prediction: 2.0
Actual Result: 4

Clump Thickness                 5
Uniformity of Cell Size         4
Uniformity of Cell Shape        6
Marginal Adhesion               8
Single Epithelial Cell Size     4
Bare Nuclei                     1
Bland Chromatin                 8
Normal Nucleoli                10
Mitoses                         1
Name: 603, dtype: int64
Model Prediction: 2.0
Actual Result: 4

Clump Thickness                 5
Uniformity of Cell Size        10
Uniformity of Cell Shape       10
Marginal Adhesion              10
Single Epithelial Cell Size     5
Bare Nuclei                     2
Bland Chromatin                 8
Normal Nucleoli                 5
Mitoses                         1
Name: 611, dtype: int64
Model Prediction: 2.0
Actual Result: 4

Clump Thickness                 5
Uniformity of Cell Size        10
Uniformity of Cell Shape       10
Marginal Adhesion              10
Single Epithelial Cell Size    10
Bare Nuclei                     2
Bland Chromatin                10
Normal Nucleoli                10
Mitoses                        10
Name: 648, dtype: int64
Model Prediction: 2.0
Actual Result: 4

Clump Thickness                5
Uniformity of Cell Size        4
Uniformity of Cell Shape       5
Marginal Adhesion              1
Single Epithelial Cell Size    8
Bare Nuclei                    1
Bland Chromatin                3
Normal Nucleoli                6
Mitoses                        1
Name: 657, dtype: int64
Model Prediction: 4.0
Actual Result: 2